In [42]:
import pandas as pd
import numpy as np
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split, cross_val_score, StratifiedKFold
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [2]:
df = pd.read_csv("/kaggle/input/iris/Iris.csv")
df.head(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [3]:
df.isnull().values.any()

False

In [4]:
print(df.dtypes)
print(df.info())

Id                 int64
SepalLengthCm    float64
SepalWidthCm     float64
PetalLengthCm    float64
PetalWidthCm     float64
Species           object
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB
None


In [9]:
df[20:40]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
20  21            5.4           3.4            1.7           0.2  Iris-setosa
21  22            5.1           3.7            1.5           0.4  Iris-setosa
22  23            4.6           3.6            1.0           0.2  Iris-setosa
23  24            5.1           3.3            1.7           0.5  Iris-setosa
24  25            4.8           3.4            1.9           0.2  Iris-setosa
25  26            5.0           3.0            1.6           0.2  Iris-setosa
26  27            5.0           3.4            1.6           0.4  Iris-setosa
27  28            5.2           3.5            1.5           0.2  Iris-setosa
28  29            5.2           3.4            1.4           0.2  Iris-setosa
29  30            4.7           3.2            1.6           0.2  Iris-setosa
30  31            4.8           3.1            1.6           0.2  Iris-setosa
31  32            5.4           3.4            1.5           0.4  Iris-setosa
32  33            5.2           4.1            1.5           0.1  Iris-setosa
33  34            5.5           4.2            1.4           0.2  Iris-setosa
34  35            4.9           3.1            1.5           0.1  Iris-setosa
35  36            5.0           3.2            1.2           0.2  Iris-setosa
36  37            5.5           3.5            1.3           0.2  Iris-setosa
37  38            4.9           3.1            1.5           0.1  Iris-setosa
38  39            4.4           3.0            1.3           0.2  Iris-setosa
39  40            5.1           3.4            1.5           0.2  Iris-setosa

In [15]:
df[49:66]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
49  50            5.0           3.3            1.4           0.2   
50  51            7.0           3.2            4.7           1.4   
51  52            6.4           3.2            4.5           1.5   
52  53            6.9           3.1            4.9           1.5   
53  54            5.5           2.3            4.0           1.3   
54  55            6.5           2.8            4.6           1.5   
55  56            5.7           2.8            4.5           1.3   
56  57            6.3           3.3            4.7           1.6   
57  58            4.9           2.4            3.3           1.0   
58  59            6.6           2.9            4.6           1.3   
59  60            5.2           2.7            3.9           1.4   
60  61            5.0           2.0            3.5           1.0   
61  62            5.9           3.0            4.2           1.5   
62  63            6.0           2.2            4.0           1.0   
63  64            6.1           2.9            4.7           1.4   
64  65            5.6           2.9            3.6           1.3   
65  66            6.7           3.1            4.4           1.4   

            Species  
49      Iris-setosa  
50  Iris-versicolor  
51  Iris-versicolor  
52  Iris-versicolor  
53  Iris-versicolor  
54  Iris-versicolor  
55  Iris-versicolor  
56  Iris-versicolor  
57  Iris-versicolor  
58  Iris-versicolor  
59  Iris-versicolor  
60  Iris-versicolor  
61  Iris-versicolor  
62  Iris-versicolor  
63  Iris-versicolor  
64  Iris-versicolor  
65  Iris-versicolor

In [13]:
df[99:106]

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
99   100            5.7           2.8            4.1           1.3   
100  101            6.3           3.3            6.0           2.5   
101  102            5.8           2.7            5.1           1.9   
102  103            7.1           3.0            5.9           2.1   
103  104            6.3           2.9            5.6           1.8   
104  105            6.5           3.0            5.8           2.2   
105  106            7.6           3.0            6.6           2.1   

             Species  
99   Iris-versicolor  
100   Iris-virginica  
101   Iris-virginica  
102   Iris-virginica  
103   Iris-virginica  
104   Iris-virginica  
105   Iris-virginica

In [24]:
RANDOM_STATE = 32
df_shuffled = shuffle(df, random_state=RANDOM_STATE).reset_index(drop=True)
print(df_shuffled.head())

    Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0   56            5.7           2.8            4.5           1.3   
1   23            4.6           3.6            1.0           0.2   
2   27            5.0           3.4            1.6           0.4   
3   57            6.3           3.3            4.7           1.6   
4  135            6.1           2.6            5.6           1.4   

           Species  
0  Iris-versicolor  
1      Iris-setosa  
2      Iris-setosa  
3  Iris-versicolor  
4   Iris-virginica  


In [64]:
X= df_shuffled.drop(["Id", "Species"],axis=1)
y= df_shuffled["Species"]

In [65]:
print(y[0:5])

0    Iris-versicolor
1        Iris-setosa
2        Iris-setosa
3    Iris-versicolor
4     Iris-virginica
Name: Species, dtype: object


In [66]:
encoder= LabelEncoder()
y= encoder.fit_transform(y)
print(y[0:5])

[1 0 0 1 2]


In [67]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=RANDOM_STATE, stratify=y
)

In [68]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [69]:
 models = {
        "LogisticRegression": LogisticRegression(max_iter=1000, random_state=RANDOM_STATE),
        "KNeighbors (k=5)": KNeighborsClassifier(n_neighbors=5),
        "SVM (rbf)": SVC(probability=False, kernel="rbf", random_state=RANDOM_STATE),
        "RandomForest": RandomForestClassifier(n_estimators=200, random_state=RANDOM_STATE),
        "GradientBoosting": GradientBoostingClassifier(n_estimators=200, random_state=RANDOM_STATE)
    }

In [70]:
CV_FOLDS = 5
cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=RANDOM_STATE)
cv_scores = {}

print(f"Running cross-validation on the training set ({CV_FOLDS} folds):")
for name, model in models.items():
    scores = cross_val_score(model, X_train, y_train, cv=cv, scoring="accuracy", n_jobs=-1)
    cv_scores[name] = {
        "mean": float(scores.mean()),
        "std": float(scores.std()),
        "all_scores": scores.tolist()
    }
    print(f"  {name:25s} mean={scores.mean():.4f} std={scores.std():.4f}")


Running cross-validation on the training set (5 folds):
  LogisticRegression        mean=0.9750 std=0.0333
  KNeighbors (k=5)          mean=0.9667 std=0.0486
  SVM (rbf)                 mean=0.9833 std=0.0333
  RandomForest              mean=0.9750 std=0.0333
  GradientBoosting          mean=0.9750 std=0.0333


In [71]:
best_model_name = max(cv_scores.items(), key=lambda kv: kv[1]["mean"])[0]
best_model = models[best_model_name]
print(f"Selected best model by CV mean accuracy: {best_model_name}")

Selected best model by CV mean accuracy: SVM (rbf)


In [72]:
best_model.fit(X_train, y_train)

SVC(random_state=32)

In [73]:
y_pred= best_model.predict(X_test)

In [76]:
acc_test = accuracy_score(y_test, y_pred)
print(f"\nTest set accuracy of best model ({best_model_name}): {acc_test:.4f}\n")
print("Classification report (test set):")
encoder.fit(df_shuffled['Species']) 
print(classification_report(y_test, y_pred, target_names=encoder.classes_))
print("Confusion matrix (test set):")
print(confusion_matrix(y_test, y_pred))



Test set accuracy of best model (SVM (rbf)): 0.9000

Classification report (test set):
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       0.89      0.80      0.84        10
 Iris-virginica       0.82      0.90      0.86        10

       accuracy                           0.90        30
      macro avg       0.90      0.90      0.90        30
   weighted avg       0.90      0.90      0.90        30

Confusion matrix (test set):
[[10  0  0]
 [ 0  8  2]
 [ 0  1  9]]
